version: '3'
services:
  app:
    container_name: node-js
    restart: always
    build: .
    ports:
      - 3000:3000
    external_links:
      - mongo
    env_file:
      - .env.production
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017